services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - backend

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vite