services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - ${NGINX_PORT}
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vite

networks:
  app-network:
    driver: bridge