services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vite

volumes:
  database:
    external: true